// Ignore any errors, it will be voided in main file
#pragma once
#include <map>
#include <string>

std::map<std::string, std::string> jakselKeywords = {
    {"which is", ";"},
    {"spill", "std::cout <<"},
    {"begitulah", "return"},
    {"kalo", "if"},
    {"gitu", "else"},
    {"nomer", "int"},
    {"nonbinary", "bool"},
    {"selama", "while"},
    {"plus", "+"},
    {"mines", "-"},
    {"is", "="},
    {"enter", "std::endl"},
    {"start oi", "{"},
    {"thats literally it", "}"},
    {"mana woi", "std::cin >>"},
    {"coba", "for"},
    {"gimme", "#include"},
    {"yang", "using namespace"},
    {"kalo ga", "else if"},
    {"sama", "=="},
    {"ga ada", "nullptr"},
    {"gak ada", "nullptr"},
    {"gak", "!"},
    {"bisa ga", "return"},
    {"kalo iya", "if"},
    {"kalo engga", "else"},
    {"then", "<<"},
    {"cekidot", "std::cout <<"},
    {"plus equals", "+="},
    {"minus equals", "-="},
    {"stop it", "break"},
    {"lanjut", "continue"},
    {"buat", "new"},
    {"hapus", "delete"},
    {"gas aja", "auto"},
    {"sambung", "++"},
    {"kurang", "--"},
    {"bikin shared", "std::make_shared"},
    {"bikin unik", "std::make_unique"},
    {"keluar", "exit(0);"},
    {"tulis", "std::cout <<"},
    {"baca", "std::cin >>"},
    {"coba loop", "for"},
    {"cek", "if"},
    {"sudah", "true"},
    {"belum", "false"},
    {"anjir", "exit(1);"},
    {"kasih tau", "//"},
    {"desimal", "double"},
    {"floaty boi", "float"},
    {"stringy boi", "std::string"},
    {"array", "std::vector"},
    {"list", "std::list"},
    {"map", "std::map"},
    {"set", "std::set"},
    {"ini", "this"},
    {"my heart", "void"},
    {"bagi", "/"},
    {"kali", "*"},
    {"mod", "%"},
    {"sama dengan", "=="},
    {"lebih dari", ">"},
    {"kurang dari", "<"},
    {"lebih dari sama dengan", ">="},
    {"kurang dari sama dengan", "<="},
    {"not sama dengan", "!="},
    {"letter", "char"}
};